apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-mysql
  labels:
    app: nest-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-sql
  template:
    metadata:
      labels:
        app: nest-sql
    spec:
      containers:
      - name: nest-sql
        image: tuansu2021998/custom-nestjs:2
        ports:
        - containerPort: 8080